### PR TITLE
add show password

### PR DESCRIPTION
**Pull request by ahmadahmadi14**
Thank you for understand login-screen. I have added image eye to show password. please review. Many Thanks.

### CODE REVIEW

**Comment by dwicao** [comment]
@ahmadahmadi14 Thank you for your Pull Request,
would be nice if you import image directly from the folder,
like this: 
```jsx
import eye from '../images/eye_black.png';
```
and on your code line 51, A bind call or arrow function in a JSX prop will create a brand new function on every single render. This is bad for performance, as it will result in the garbage collector being invoked way more than is necessary.
solution, do like this:
```jsx
constructor() {
  this.showPass = this.showPass.bind(this);
}
```
```jsx
<TouchableOpacity onPress={this.showPass}>
```

**Comment by ahmadahmadi14** [comment]
It is good idea. 

But when I use your advice about arrow function is error. my references.
`https://www.tutorialspoint.com/react_native/react_native_state.htm`.

Do you have some advice?

**Comment by dwicao** [comment]
@ahmadahmadi14 I've been improved your code, check [HERE](https://jsfiddle.net/dwicao/w3h3hb3j/1/)
Any complaint? if you have any error please let me know, thank you

**Comment by ahmadahmadi14** [comment]
@dwicao . It is great, before your solution I have a little obstacle. I forgot put a variable 'press: false'. I have pushed to contribution in your repository. It may help you and me soon.

**Comment by dwicao** [comment]
@ahmadahmadi14 I'll Merge this Pull Request, thank you for your contribution 😄

**Pull request merged**
